use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use tempfile::tempdir;
use xtask::harness::scan_common::{
    classify_file, resolve_external_test_modules, strip_test_items, FileClass,
};
use xtask::workspace_index::WorkspaceIndex;

#[test]
fn test_classify_file_generated_header() {
    let path = PathBuf::from("crates/my_crate/src/generated.rs");
    let content = "// @generated\npub fn foo() {}\n";
    let external_test_files = HashSet::new();

    let class = classify_file(&path, content, &external_test_files);
    assert_eq!(class, FileClass::Generated);

    let content_flatbuffers =
        "// automatically generated by the FlatBuffers compiler, do not modify\n";
    let class_fb = classify_file(&path, content_flatbuffers, &external_test_files);
    assert_eq!(class_fb, FileClass::Generated);
}

#[test]
fn test_fixture_mod_tests_external_file() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    let src_dir = root.join("crates").join("my_crate").join("src");
    fs::create_dir_all(&src_dir).unwrap();

    let lib_rs = src_dir.join("lib.rs");
    let lib_content = "#[cfg(test)]\nmod tests;\n\npub fn prod_fn() {}\n";
    fs::write(&lib_rs, lib_content).unwrap();

    let tests_rs = src_dir.join("tests.rs");
    let tests_content = "pub fn helper() {}\n";
    fs::write(&tests_rs, tests_content).unwrap();

    let file_ast = syn::parse_str::<syn::File>(lib_content).unwrap();
    let mut external_test_files = HashSet::new();
    resolve_external_test_modules(&lib_rs, &file_ast, &mut external_test_files);

    assert!(
        external_test_files.contains(&tests_rs)
            || external_test_files
                .contains(&tests_rs.canonicalize().unwrap_or_else(|_| tests_rs.clone()))
    );

    let class_tests_rs = classify_file(&tests_rs, tests_content, &external_test_files);
    assert_eq!(class_tests_rs, FileClass::Test);

    let class_lib_rs = classify_file(&lib_rs, lib_content, &external_test_files);
    assert_eq!(class_lib_rs, FileClass::Production);
}

#[test]
fn test_fixture_inline_cfg_test_mod_strip() {
    let code = r#"
pub fn production_fn() -> u32 {
    42
}

#[cfg(test)]
mod token_tests {
    use super::*;

    #[test]
    fn my_test() {
        assert_eq!(production_fn().unwrap(), 42);
    }
}

pub struct ProdStruct;
"#;

    let file_ast = syn::parse_str::<syn::File>(code).unwrap();
    let stripped = strip_test_items(&file_ast);
    let stripped_file = &stripped.file;

    let printed = quote::quote!(#stripped_file).to_string();

    assert!(printed.contains("production_fn"));
    assert!(printed.contains("ProdStruct"));
    assert!(!printed.contains("token_tests"));
    assert!(!printed.contains("my_test"));
    assert_eq!(stripped.removed_test_fn_count, 1);
}

#[test]
fn test_workspace_index_caching_and_reparse_count() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    let src_dir = root.join("crates").join("my_crate").join("src");
    fs::create_dir_all(&src_dir).unwrap();

    let lib_rs = src_dir.join("lib.rs");
    fs::write(&lib_rs, "pub fn hello() {}\n").unwrap();

    // First run: parses files
    let idx1 = WorkspaceIndex::build_from_root(root).unwrap();
    assert!(idx1.parsed_files_count > 0);

    // Second run on unchanged repo: should parse 0 files
    let idx2 = WorkspaceIndex::build_from_root(root).unwrap();
    assert_eq!(idx2.parsed_files_count, 0);
}
