// FILE-CONTEXT
// ZWECK: Agent Memory Facade (Ring 4) — Provides a clean remember/recall/forget/relate API for AI Agents.
// INVARIANTEN: #![forbid(unsafe_code)]; Zero panic doctrine (.unwrap/.expect forbidden); Wraps Contextra engine without changing business logic.

use contextra_core::error::ContextraError;
use contextra_db::{Contextra, ProvenanceRecord, SearchResult};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fmt;
use std::sync::Arc;

/// Opaque identifier for a memory stored via `AgentMemory`.
///
/// Wraps the underlying document ID string used by `Contextra`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MemoryId(String);

impl MemoryId {
    /// Creates a new `MemoryId` from a string identifier.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Returns a string slice reference to the underlying memory ID.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<String> for MemoryId {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl From<&str> for MemoryId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl AsRef<str> for MemoryId {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for MemoryId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Opaque identifier for an n-ary relation (hyperedge) stored via `AgentMemory::relate_n_ary`.
///
/// Wraps the underlying 64-bit hyperedge ID generated by the knowledge graph engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RelationId(pub u64);

impl fmt::Display for RelationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RelationId({})", self.0)
    }
}

/// Representation of a recalled memory record.
///
/// Derived from `SearchResult` provided by `Contextra::search_text` or hybrid queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Memory {
    /// Document identifier string.
    pub id: String,
    /// Relevance / similarity score.
    pub score: f32,
    /// Optional metadata associated with the memory entry.
    pub metadata: Option<Value>,
    /// Matched signal types (e.g., text, vector, graph).
    pub matched_signals: Vec<String>,
    /// Detailed score provenance breakdown.
    pub provenance: Option<ProvenanceRecord>,
}

impl From<SearchResult> for Memory {
    fn from(res: SearchResult) -> Self {
        Self {
            id: res.id,
            score: res.score,
            metadata: res.metadata,
            matched_signals: res.matched_signals,
            provenance: res.provenance,
        }
    }
}

/// High-level facade for agent-oriented memory management (`remember`, `recall`, `forget`, `relate`).
///
/// `AgentMemory` wraps an underlying `Contextra` engine instance, providing agent-friendly terms
/// for text memory persistence, semantic retrieval, deletion, and knowledge graph relations.
#[derive(Clone)]
pub struct AgentMemory {
    engine: Arc<Contextra>,
}

impl AgentMemory {
    /// Constructs a new `AgentMemory` wrapper around a `Contextra` engine instance.
    pub fn new(engine: Contextra) -> Self {
        Self {
            engine: Arc::new(engine),
        }
    }

    /// Constructs a new `AgentMemory` wrapper around an `Arc<Contextra>` engine instance.
    pub fn new_arc(engine: Arc<Contextra>) -> Self {
        Self { engine }
    }

    /// Returns a reference to the underlying `Contextra` engine instance.
    pub fn engine(&self) -> &Contextra {
        &self.engine
    }

    /// Stores a text memory entry with optional JSON metadata.
    ///
    /// Generates a unique memory identifier and delegates directly to `Contextra::insert_text_only`.
    pub async fn remember(
        &self,
        text: &str,
        metadata: Option<Value>,
    ) -> Result<MemoryId, ContextraError> {
        let id = uuid::Uuid::new_v4().to_string();
        self.engine.insert_text_only(&id, text, metadata).await?;
        Ok(MemoryId(id))
    }

    /// Retrieves top-k matching memories for a natural language query text string.
    ///
    /// Delegates directly to `Contextra::search_text` and transforms each `SearchResult` into a `Memory`.
    pub async fn recall(&self, query: &str, k: usize) -> Result<Vec<Memory>, ContextraError> {
        let results = self.engine.search_text(query, k).await?;
        Ok(results.into_iter().map(Memory::from).collect())
    }

    /// Deletes a memory entry by its `MemoryId`.
    ///
    /// Delegates directly to `Contextra::delete`.
    pub async fn forget(&self, id: &MemoryId) -> Result<(), ContextraError> {
        self.engine.delete(id.as_str()).await
    }

    /// Establishes a directed knowledge-graph relationship between two memories with a given label.
    ///
    /// Delegates directly to `Contextra::relate`.
    pub async fn relate(
        &self,
        from: &MemoryId,
        to: &MemoryId,
        label: &str,
    ) -> Result<(), ContextraError> {
        self.engine.relate(from.as_str(), to.as_str(), label).await
    }

    /// Establishes an n-ary hyperedge relationship connecting two or more memories, each bound to a specific role.
    ///
    /// # Role Semantics
    /// The underlying engine maps each role string (e.g., `"author"`, `"reviewer"`) deterministically
    /// to a `RoleId`. Identical role strings produce the exact same `RoleId`.
    ///
    /// # Early Validation
    /// Validates inputs before delegating to `Collection::relate_n_ary`:
    /// - `predicate` must not be empty.
    /// - `participants` must contain at least 2 entries.
    /// - Role strings in `participants` must not be empty.
    pub async fn relate_n_ary(
        &self,
        predicate: &str,
        participants: &[(&MemoryId, &str)],
        source: Option<&MemoryId>,
    ) -> Result<RelationId, ContextraError> {
        if predicate.trim().is_empty() {
            return Err(ContextraError::InvalidInput(
                "relate_n_ary predicate must not be empty".to_string(),
            ));
        }

        if participants.len() < 2 {
            return Err(ContextraError::InvalidInput(format!(
                "relate_n_ary requires at least 2 participants, found {}",
                participants.len()
            )));
        }

        for (_, role) in participants {
            if role.trim().is_empty() {
                return Err(ContextraError::InvalidInput(
                    "relate_n_ary participant role must not be empty".to_string(),
                ));
            }
        }

        let collection = self.engine.collection("default").await?;
        let participant_tuples: Vec<(&str, &str)> = participants
            .iter()
            .map(|(mem_id, role)| (mem_id.as_str(), *role))
            .collect();
        let source_str = source.map(|s| s.as_str());

        let hyperedge_id = collection
            .relate_n_ary(predicate, &participant_tuples, source_str)
            .await?;

        Ok(RelationId(hyperedge_id.inner()))
    }
}
