//! Random number generator port trait and deterministic SplitMix64 implementation.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

/// Port trait for random number generators, enabling deterministic testing by decoupling
/// non-deterministic entropy sources.
pub trait Rng: Send + Sync + 'static {
    /// Generates the next pseudorandom 64-bit unsigned integer.
    fn next_u64(&self) -> u64;

    /// Fills `dest` with pseudorandom bytes generated by this RNG.
    fn fill_bytes(&self, dest: &mut [u8]);

    /// Returns a pseudorandom `f64` value in the half-open interval `[0.0, 1.0)`
    /// with 53 bits of precision.
    fn next_unit_f64(&self) -> f64;
}

/// A fast, deterministic 64-bit pseudorandom number generator using SplitMix64
/// with atomic state transitions (`AtomicU64`).
///
/// Lock-free and thread-safe without requiring `Mutex`.
///
/// # Entropy Seeding
/// Note that non-deterministic entropy seeding (e.g., via `OsRng` or system entropy)
/// is the responsibility of the Composition Root. Application entry points should gather entropy
/// at startup and pass the initial seed to [`SeededRng::new`].
#[derive(Debug)]
pub struct SeededRng {
    state: AtomicU64,
}

const GOLDEN_RATIO_64: u64 = 0x9e37_79b9_7f4a_7c15;

impl SeededRng {
    /// Creates a new [`SeededRng`] initialized with the given seed.
    pub fn new(seed: u64) -> Self {
        Self {
            state: AtomicU64::new(seed),
        }
    }
}

impl Rng for SeededRng {
    fn next_u64(&self) -> u64 {
        let z = self
            .state
            .fetch_add(GOLDEN_RATIO_64, Ordering::SeqCst)
            .wrapping_add(GOLDEN_RATIO_64);
        let mut z = z;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn fill_bytes(&self, mut dest: &mut [u8]) {
        while !dest.is_empty() {
            let val = self.next_u64();
            let bytes = val.to_le_bytes();
            let len = dest.len().min(8);
            dest[..len].copy_from_slice(&bytes[..len]);
            dest = &mut dest[len..];
        }
    }

    fn next_unit_f64(&self) -> f64 {
        // Extract 53 bits for f64 mantissa: (next_u64() >> 11) / 2^53
        let mantissa = self.next_u64() >> 11;
        (mantissa as f64) * (1.0 / (1u64 << 53) as f64)
    }
}

impl<T: Rng + ?Sized> Rng for Arc<T> {
    fn next_u64(&self) -> u64 {
        (**self).next_u64()
    }

    fn fill_bytes(&self, dest: &mut [u8]) {
        (**self).fill_bytes(dest);
    }

    fn next_unit_f64(&self) -> f64 {
        (**self).next_unit_f64()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn _assert_dyn_rng(_: Option<&dyn Rng>) {}

    #[test]
    fn test_seeded_rng_reproducibility() {
        let rng1 = SeededRng::new(12345);
        let rng2 = SeededRng::new(12345);

        for _ in 0..10 {
            assert_eq!(rng1.next_u64(), rng2.next_u64());
        }
    }

    #[test]
    fn test_seeded_rng_different_seeds() {
        let rng1 = SeededRng::new(100);
        let rng2 = SeededRng::new(200);

        assert_ne!(rng1.next_u64(), rng2.next_u64());
    }

    #[test]
    fn test_next_unit_f64_in_bounds() {
        let rng = SeededRng::new(42);
        for _ in 0..1000 {
            let val = rng.next_unit_f64();
            assert!((0.0..1.0).contains(&val), "Value out of bounds: {val}");
        }
    }

    #[test]
    fn test_fill_bytes_lengths() {
        let rng = SeededRng::new(999);

        for len in [0, 1, 7, 8, 9] {
            let mut buf = vec![0u8; len];
            rng.fill_bytes(&mut buf);
            assert_eq!(buf.len(), len);
        }
    }

    #[test]
    fn test_arc_dyn_rng() {
        let rng: Arc<dyn Rng> = Arc::new(SeededRng::new(777));
        _assert_dyn_rng(Some(rng.as_ref()));

        let mut buf = [0u8; 4];
        rng.fill_bytes(&mut buf);
        let f = rng.next_unit_f64();
        assert!((0.0..1.0).contains(&f));
    }
}
