//! Random number generator port trait and deterministic SplitMix64 implementation.

use std::collections::hash_map::RandomState;
use std::hash::{BuildHasher, Hasher};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

static ENTROPY_COUNTER: AtomicU64 = AtomicU64::new(1);

/// Port trait for random number generators, enabling deterministic testing by decoupling
/// non-deterministic entropy sources.
pub trait Rng: Send + Sync + 'static {
    /// Generates the next pseudorandom 64-bit unsigned integer.
    fn next_u64(&self) -> u64;

    /// Fills `dest` with pseudorandom bytes generated by this RNG.
    fn fill_bytes(&self, dest: &mut [u8]);

    /// Returns a pseudorandom `f64` value in the half-open interval `[0.0, 1.0)`
    /// with 53 bits of precision.
    fn next_unit_f64(&self) -> f64;
}

/// A fast, deterministic 64-bit pseudorandom number generator using SplitMix64
/// with atomic state transitions (`AtomicU64`).
///
/// Lock-free and thread-safe without requiring `Mutex`.
///
/// # Entropy Seeding
/// Note that non-deterministic entropy seeding (e.g., via `OsRng` or system entropy)
/// is the responsibility of the Composition Root. Application entry points should gather entropy
/// at startup and pass the initial seed to [`SeededRng::new`].
#[derive(Debug)]
pub struct SeededRng {
    state: AtomicU64,
}

const GOLDEN_RATIO_64: u64 = 0x9e37_79b9_7f4a_7c15;

impl SeededRng {
    /// Creates a new [`SeededRng`] initialized with the given seed.
    pub fn new(seed: u64) -> Self {
        Self {
            state: AtomicU64::new(seed),
        }
    }

    /// Creates a new [`SeededRng`] seeded from process/runtime entropy.
    ///
    /// # Non-Cryptographic Usage
    /// This entropy source uses [`std::collections::hash_map::RandomState`] and an internal counter.
    /// It is intended strictly for non-cryptographic usages such as jitter, load balancing,
    /// and randomized algorithm initialization. Cryptographic keys and salts MUST use
    /// dedicated cryptographic RNGs (`OsRng`).
    ///
    /// # Composition Root Architecture
    /// Only Composition Roots (application entry points) should construct a [`SeededRng`] via `from_entropy`.
    /// Internal library logic MUST accept an injected [`Rng`] instance instead of calling `from_entropy` directly.
    pub fn from_entropy() -> Self {
        let counter = ENTROPY_COUNTER.fetch_add(1, Ordering::Relaxed);

        let mut hasher1 = RandomState::new().build_hasher();
        hasher1.write_u64(counter);
        let h1 = hasher1.finish();

        let mut hasher2 = RandomState::new().build_hasher();
        hasher2.write_u64(h1);
        let h2 = hasher2.finish();

        let seed = h1 ^ h2.rotate_left(32) ^ GOLDEN_RATIO_64.wrapping_mul(counter);
        Self::new(seed)
    }
}

impl Rng for SeededRng {
    fn next_u64(&self) -> u64 {
        let z = self
            .state
            .fetch_add(GOLDEN_RATIO_64, Ordering::SeqCst)
            .wrapping_add(GOLDEN_RATIO_64);
        let mut z = z;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn fill_bytes(&self, mut dest: &mut [u8]) {
        while !dest.is_empty() {
            let val = self.next_u64();
            let bytes = val.to_le_bytes();
            let len = dest.len().min(8);
            dest[..len].copy_from_slice(&bytes[..len]);
            dest = &mut dest[len..];
        }
    }

    fn next_unit_f64(&self) -> f64 {
        // Extract 53 bits for f64 mantissa: (next_u64() >> 11) / 2^53
        let mantissa = self.next_u64() >> 11;
        (mantissa as f64) * (1.0 / (1u64 << 53) as f64)
    }
}

impl<T: Rng + ?Sized> Rng for Arc<T> {
    fn next_u64(&self) -> u64 {
        (**self).next_u64()
    }

    fn fill_bytes(&self, dest: &mut [u8]) {
        (**self).fill_bytes(dest);
    }

    fn next_unit_f64(&self) -> f64 {
        (**self).next_unit_f64()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn _assert_dyn_rng(_: Option<&dyn Rng>) {}

    #[test]
    fn test_seeded_rng_reproducibility() {
        let rng1 = SeededRng::new(12345);
        let rng2 = SeededRng::new(12345);

        for _ in 0..10 {
            assert_eq!(rng1.next_u64(), rng2.next_u64());
        }
    }

    #[test]
    fn test_from_entropy_different_sequences() {
        let rng1 = SeededRng::from_entropy();
        let rng2 = SeededRng::from_entropy();

        let draws1: Vec<u64> = (0..4).map(|_| rng1.next_u64()).collect();
        let draws2: Vec<u64> = (0..4).map(|_| rng2.next_u64()).collect();

        assert_ne!(
            draws1, draws2,
            "from_entropy instances generated identical 4-draw sequences"
        );
    }

    #[test]
    fn test_seeded_rng_different_seeds() {
        let rng1 = SeededRng::new(100);
        let rng2 = SeededRng::new(200);

        assert_ne!(rng1.next_u64(), rng2.next_u64());
    }

    #[test]
    fn test_next_unit_f64_in_bounds() {
        let rng = SeededRng::new(42);
        for _ in 0..1000 {
            let val = rng.next_unit_f64();
            assert!((0.0..1.0).contains(&val), "Value out of bounds: {val}");
        }
    }

    #[test]
    fn test_fill_bytes_lengths() {
        let rng = SeededRng::new(999);

        for len in [0, 1, 7, 8, 9] {
            let mut buf = vec![0u8; len];
            rng.fill_bytes(&mut buf);
            assert_eq!(buf.len(), len);
        }
    }

    #[test]
    fn test_arc_dyn_rng() {
        let rng: Arc<dyn Rng> = Arc::new(SeededRng::new(777));
        _assert_dyn_rng(Some(rng.as_ref()));

        let mut buf = [0u8; 4];
        rng.fill_bytes(&mut buf);
        let f = rng.next_unit_f64();
        assert!((0.0..1.0).contains(&f));
    }
}
