[package]
name = "contextra-wire-fuzz" # <!-- crate-ref-ignore -->
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.4", features = ["derive"] }
bytes = "1"
flatbuffers = "24"
contextra-wire = { path = ".." }

[[bin]]
name = "fuzz_flatbuffers_ipc"
path = "fuzz_targets/fuzz_flatbuffers_ipc.rs"
test = false
doc = false
