//! Shared scanning infrastructure and file classification for xtask tools.
//!
//! Regex usage justification:
//! Regex is used strictly for non-AST string pattern matching: matching generated code header lines
//! (such as `@generated` or FlatBuffers headers in the first 5 lines of a file), filename pattern matching
//! (e.g. `tests.rs`, `*_test.rs`), path segment checks, and word-boundary text reference scanning in non-Rust files.
//! All Rust AST analysis (items, attributes, modules, declarations) is performed using `syn`.

use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use syn::visit_mut::VisitMut;

/// Classification of a Rust source file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FileClass {
    Generated,
    Test,
    Production,
}

/// Result of stripping test items from a `syn::File`.
#[derive(Debug)]
pub struct StripResult {
    pub file: syn::File,
    pub removed_test_fn_count: usize,
}

/// Classifies a Rust source file under `crates/<crate>/`.
///
/// Order of evaluation (binding):
/// a) GENERATED if one of the first 5 lines contains "@generated" or "automatically generated by the FlatBuffers compiler" (case-insensitive).
/// b) TEST if filename is tests.rs, test.rs, or ends with _tests.rs / _test.rs; or path component is tests, test, or benches; or file is in `external_test_files`.
/// c) PRODUCTION otherwise.
pub fn classify_file(
    file_path: &Path,
    content: &str,
    external_test_files: &HashSet<PathBuf>,
) -> FileClass {
    if is_generated(content) {
        return FileClass::Generated;
    }
    if is_test_file_path(file_path, external_test_files) {
        return FileClass::Test;
    }
    FileClass::Production
}

fn is_generated(content: &str) -> bool {
    content.lines().take(5).any(|line| {
        let l = line.to_lowercase();
        l.contains("@generated")
            || l.contains("automatically generated by the flatbuffers compiler")
    })
}

fn is_test_file_path(file_path: &Path, external_test_files: &HashSet<PathBuf>) -> bool {
    let file_name = file_path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or_default();

    if file_name == "tests.rs"
        || file_name == "test.rs"
        || file_name.ends_with("_tests.rs")
        || file_name.ends_with("_test.rs")
    {
        return true;
    }

    for comp in file_path.components() {
        let s = comp.as_os_str().to_str().unwrap_or_default();
        if s == "tests" || s == "test" || s == "benches" {
            return true;
        }
    }

    let norm = normalize_path(file_path);
    external_test_files.contains(file_path) || external_test_files.contains(&norm)
}

fn normalize_path(p: &Path) -> PathBuf {
    p.canonicalize().unwrap_or_else(|_| p.to_path_buf())
}

/// Returns true if the attribute slice contains `#[cfg(test)]`.
pub fn has_cfg_test_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        if attr.path().is_ident("cfg") {
            if let Ok(meta) = attr.parse_args::<syn::Meta>() {
                if let syn::Meta::Path(p) = meta {
                    return p.is_ident("test");
                }
            }
            if let syn::Meta::List(list) = &attr.meta {
                let tokens = list.tokens.to_string();
                let trimmed = tokens.trim();
                if trimmed == "test"
                    || trimmed.starts_with("test,")
                    || trimmed.ends_with(", test")
                    || trimmed.contains(", test,")
                {
                    return true;
                }
            }
        }
        false
    })
}

/// Returns true if the attribute is `#[test]` or `#[tokio::test]`.
pub fn has_test_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        let segs: Vec<String> = attr
            .path()
            .segments
            .iter()
            .map(|s| s.ident.to_string())
            .collect();
        if segs == vec!["test"] {
            return true;
        }
        if segs == vec!["tokio", "test"] {
            return true;
        }
        false
    })
}

/// Resolves module directory V for a file D.
///
/// If D is mod.rs, lib.rs, or main.rs, V is the parent directory of D.
/// Otherwise, V is the parent directory of D plus "/" plus the file stem of D.
pub fn get_module_dir(file_path: &Path) -> PathBuf {
    let parent = file_path.parent().unwrap_or_else(|| Path::new("."));
    let file_name = file_path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or_default();

    if file_name == "mod.rs" || file_name == "lib.rs" || file_name == "main.rs" {
        parent.to_path_buf()
    } else {
        let stem = file_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        parent.join(stem)
    }
}

/// Discovers external test files referenced via `#[cfg(test)] mod <name>;` in `file_ast`.
pub fn resolve_external_test_modules(
    file_path: &Path,
    file_ast: &syn::File,
    external_test_files: &mut HashSet<PathBuf>,
) {
    let mod_dir = get_module_dir(file_path);
    find_cfg_test_mods_in_items(&file_ast.items, &mod_dir, external_test_files);
}

fn find_cfg_test_mods_in_items(
    items: &[syn::Item],
    curr_dir: &Path,
    external_test_files: &mut HashSet<PathBuf>,
) {
    for item in items {
        if let syn::Item::Mod(m) = item {
            if has_cfg_test_attr(&m.attrs) {
                if m.content.is_none() {
                    let mod_name = m.ident.to_string();
                    let cand1 = curr_dir.join(format!("{}.rs", mod_name));
                    let cand2 = curr_dir.join(&mod_name).join("mod.rs");

                    if cand1.exists() {
                        external_test_files.insert(cand1.clone());
                        if let Ok(norm) = cand1.canonicalize() {
                            external_test_files.insert(norm);
                        }
                    } else if cand2.exists() {
                        external_test_files.insert(cand2.clone());
                        if let Ok(norm) = cand2.canonicalize() {
                            external_test_files.insert(norm);
                        }
                    }
                }
            } else if let Some((_, inline_items)) = &m.content {
                let sub_dir = curr_dir.join(m.ident.to_string());
                find_cfg_test_mods_in_items(inline_items, &sub_dir, external_test_files);
            }
        }
    }
}

/// Harness command entry point for `scan-common`.
pub fn run_scan_common(_args: &[String]) -> i32 {
    println!("xtask scan-common: Shared scanning infrastructure module loaded.");
    0
}

/// Strips test items from a `syn::File` while leaving parent/surrounding code intact.
///
/// Removes:
/// - `#[cfg(test)]` on a `mod` item with body (content.is_some()).
/// - `#[cfg(test)]` on `fn`, `impl`, `struct`, `enum`, `const`, `static`, `use`.
/// - `#[test]` or `#[tokio::test]` on functions (counting removed test functions).
pub fn strip_test_items(file_ast: &syn::File) -> StripResult {
    let mut file = file_ast.clone();
    let mut folder = TestItemStripper {
        removed_test_fn_count: 0,
    };
    folder.visit_file_mut(&mut file);
    StripResult {
        file,
        removed_test_fn_count: folder.removed_test_fn_count,
    }
}

struct TestItemStripper {
    removed_test_fn_count: usize,
}

impl TestItemStripper {
    fn count_test_fns_in_item(&mut self, item: &syn::Item) {
        match item {
            syn::Item::Fn(f) => {
                if has_test_attr(&f.attrs) {
                    self.removed_test_fn_count += 1;
                }
            }
            syn::Item::Mod(m) => {
                if let Some((_, items)) = &m.content {
                    for it in items {
                        self.count_test_fns_in_item(it);
                    }
                }
            }
            _ => {}
        }
    }

    fn should_remove_item(&mut self, item: &syn::Item) -> bool {
        match item {
            syn::Item::Mod(m) => {
                if has_cfg_test_attr(&m.attrs) && m.content.is_some() {
                    self.count_test_fns_in_item(item);
                    return true;
                }
                false
            }
            syn::Item::Fn(f) => {
                let is_test_fn = has_test_attr(&f.attrs);
                let is_cfg_test = has_cfg_test_attr(&f.attrs);
                if is_test_fn {
                    self.removed_test_fn_count += 1;
                    return true;
                }
                if is_cfg_test {
                    return true;
                }
                false
            }
            syn::Item::Impl(i) => has_cfg_test_attr(&i.attrs),
            syn::Item::Struct(s) => has_cfg_test_attr(&s.attrs),
            syn::Item::Enum(e) => has_cfg_test_attr(&e.attrs),
            syn::Item::Const(c) => has_cfg_test_attr(&c.attrs),
            syn::Item::Static(s) => has_cfg_test_attr(&s.attrs),
            syn::Item::Use(u) => has_cfg_test_attr(&u.attrs),
            _ => false,
        }
    }

    fn filter_items(&mut self, items: &mut Vec<syn::Item>) {
        let mut i = 0;
        while i < items.len() {
            if self.should_remove_item(&items[i]) {
                items.remove(i);
            } else {
                self.visit_item_mut(&mut items[i]);
                i += 1;
            }
        }
    }
}

impl VisitMut for TestItemStripper {
    fn visit_file_mut(&mut self, file: &mut syn::File) {
        self.filter_items(&mut file.items);
    }

    fn visit_item_mod_mut(&mut self, m: &mut syn::ItemMod) {
        if let Some((_, ref mut items)) = m.content {
            self.filter_items(items);
        }
    }
}
