name: Update Prompter-Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-prompter-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Generate Prompter Data
        run: cargo run -p xtask -- gen-prompter-data
